# M1L7 Data Challenge:  Data Manipulation 

 We'll continue to work with UFO sighting data.

### **Dataset:** [UFO Sightings](https://www.kaggle.com/datasets/jonwright13/ufo-sightings-around-the-world-better?resource=download) -- This is also in your data folder 

### **Objectives:**

- Use string methods to manipulate data 
- Filter Data 
- Work more with dates in Python



**Let's get started!**

### Step 1:  Import Pandas & Numpy

In [3]:
# Import Pandas 
import pandas as pd
import numpy as np

### Step 2: Load the dataset (csv file stored in the data folder) into a Pandas DataFrame called `ufo`

- The file is callled `ufo-sightings.csv`

In [28]:
ufo = pd.read_csv('/Users/Marcy_Student/Downloads/ufo-sightings-transformed.csv')

### Step 3: Explore the Data

Use any method(s) of your choice to look at the data and explore it

In [27]:

ufo.head()

,Unnamed: 0,Date_time,date_documented,Year,Month,Hour,Season,Country_Code,Country,Region,Locale,latitude,longitude,UFO_shape,length_of_encounter_seconds,Encounter_Duration,Description
0,0,1949-10-10 20:30:00,4/27/2004,1949,10,20,Autumn,USA,United States,Texas,San Marcos,29.883056,-97.941111,CYLINDER,2700.0,45 minutes,This event took place in early fall around 194...
1,1,1949-10-10 21:00:00,12/16/2005,1949,10,21,Autumn,USA,United States,Texas,Bexar County,29.384210,-98.581082,LIGHT,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...
2,2,1955-10-10 17:00:00,1/21/2008,1955,10,17,Autumn,GBR,United Kingdom,England,Chester,53.200000,-2.916667,CIRCLE,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...
3,3,1956-10-10 21:00:00,1/17/2004,1956,10,21,Autumn,USA,United States,Texas,Edna,28.978333,-96.645833,CIRCLE,20.0,1/2 hour,My older brother and twin sister were leaving ...
4,4,1960-10-10 20:00:00,1/22/2004,1960,10,20,Autumn,USA,United States,Hawaii,Kaneohe,21.418056,-157.803611,LIGHT,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...

### Step 4:  Clean the UFO_shape column 
- Make the column all uppercase 
- Strip off any leading and trailing spaces 

Even if there are no actual spaces; it is still good practice to trim off spaces even if you can't see space with the naked eye

Hint:  You will use both `str.upper()` and `str.strip()` -- you can do it in one step or two separate steps

In [26]:
ufo['UFO_shape']= ufo['UFO_shape'].str.upper().str.strip()

### Step 5:  Use `pd.crosstab` to sum the number of shapes seen by season

- Add a comment of a main takeaway from the output

In [25]:
pd.crosstab(ufo['UFO_shape'], ufo['Season'])
#Add comment here:

Season     Autumn  Spring  Summer  Winter
UFO_shape
CHANGED         0       0       1       0
CHANGING      552     443     565     402
CHEVRON       333     215     225     179
CIGAR         519     421     783     334
CIRCLE       2002    1464    2604    1537
CONE           85      70      84      77
CRESCENT        1       1       0       0
CROSS          63      53      70      47
CYLINDER      332     272     449     230
DELTA           3       1       2       1
DIAMOND       309     244     349     276
DISK         1320    1052    1973     868
DOME            0       1       0       0
EGG           176     159     260     164
FIREBALL     1789    1038    2025    1356
FLARE           1       0       0       0
FLASH         387     253     420     268
FORMATION     726     546     684     501
HEXAGON         0       0       0       1
LIGHT        4458    3229    5518    3360
OTHER        1561    1155    1853    1080
OVAL          962     762    1258     751
PYRAMID         0       0       0       1
RECTANGLE     343     261     452     240
ROUND           1       0       0       1
SPHERE       1365    1114    1884    1024
TEARDROP      213     149     234     154
TRIANGLE     2272    1742    2322    1529
UNKNOWN      1488    1154    1753    1189

In [23]:
# Run this cell without changes before moving on to step 6!

ufo['Date_time'] = pd.to_datetime(ufo['Date_time'], format="%Y-%m-%d %H:%M:%S")

### Step 6:  Filter the data where the region is equal to `New York`

In [24]:
ufo_ny = ufo[ufo['Region']== "New York"]
print(ufo_ny)

       Unnamed: 0           Date_time date_documented  Year  Month  Hour  \
12             12 1970-10-10 16:00:00       5/11/2000  1970     10    16
27             27 1978-10-10 02:00:00        2/1/2007  1978     10     2
28             28 1979-10-10 00:00:00       4/16/2005  1979     10     0
38             38 1984-10-10 22:00:00       8/10/1999  1984     10    22
40             40 1986-10-10 20:00:00       10/8/2007  1986     10    20
...           ...                 ...             ...   ...    ...   ...
80276       80276 2011-09-09 20:30:00       5/13/2012  2011      9    20
80279       80279 2011-09-09 21:15:00      10/10/2011  2011      9    21
80299       80299 2012-09-09 20:10:00       9/24/2012  2012      9    20
80304       80304 2012-09-09 21:00:00       9/24/2012  2012      9    21
80310       80310 2013-09-09 01:50:00       9/30/2013  2013      9     1

       Season Country_Code        Country    Region         Locale   latitude  \
12     Autumn          USA  United States  New York  Nassau County  40.668611
27     Autumn          USA  United States  New York    Alden Manor  40.700833
28     Autumn          USA  United States  New York   Poughkeepsie  41.700278
38     Autumn          USA  United States  New York   White Plains  41.033889
40     Autumn          USA  United States  New York         Holmes  41.523427
...       ...          ...            ...       ...            ...        ...
80276  Autumn          USA  United States  New York      Rochester  43.154722
80279  Autumn          USA  United States  New York        Montauk  41.035833
80299  Autumn          USA  United States  New York    Alden Manor  40.700833
80304  Autumn          USA  United States  New York       New York  40.714167
80310  Autumn          USA  United States  New York        Buffalo  42.886389

       longitude  UFO_shape  length_of_encounter_seconds Encounter_Duration  \
12    -73.527500       DISK                       1800.0            30 min.
27    -73.713333  RECTANGLE                        300.0               5min
28    -73.921389    CHEVRON                        900.0         15 minutes
38    -73.763333  FORMATION                         20.0      15-20 seconds
40    -73.646795    CHEVRON                        180.0          3 minutes
...          ...        ...                          ...                ...
80276 -77.615833     CIRCLE                         60.0               1min
80279 -71.955000   CYLINDER                       2100.0    approx. 35 mins
80299 -73.713333     CIRCLE                        600.0         10 minutes
80304 -74.006389      LIGHT                       1290.0              21:30
80310 -78.878611   TRIANGLE                        180.0          3 minutes

                                             Description
12              silver disc seen by family and neighbors
27     A memory I will never forget that happened men...
28     1/4 moon-like&#44  its &#39chord&#39 or flat s...
38     Saw a hugh object in sky with lights intermitt...
40     Football Field Sized Chevron with bright white...
...                                                  ...
80276  Amber/orange balls 1 following the other chang...
80279  Yellow to orange colors radiating above and be...
80299  Orange lights seen in Elmont&#44 Long Island&#...
80304  Glowing&#44 circular lights visible in the clo...
80310    Massive Flat Black triangle  with 3 red lights.

[3235 rows x 17 columns]

### Step 7:  Get the most recent `Date_time` that a UFO was sighted in New York 

Hint:  Make sure you saved your filtered data from Step 6 to a new dataframe object aka varaible.  You can use `.max()` right after a column name to get the max of that column

You are using the `Date_time` column for this question

In [10]:
ufo_ny['Date_time'].max()

Timestamp('2014-05-05 23:04:00')

## Above and Beyond (AAB)  -- OPTIONAL

### Question 1:  How many days have passed between the first UFO sighting in NY and the most recent sighting in NY based on this data?

In [43]:
ufo_ny['Date_time'].max() - ufo_ny['Date_time'].min()

Timedelta('30654 days 01:04:00')

### Question 2:  Filter the data where UFO_shape is `UNKNOWN` and the Region is `New York`

In [47]:
ufo_ny[ufo_ny['UFO_shape'] == "UNKNOWN"]
print(ufo_ny)

       Unnamed: 0           Date_time date_documented  Year  Month  Hour  \
12             12 1970-10-10 16:00:00       5/11/2000  1970     10    16
27             27 1978-10-10 02:00:00        2/1/2007  1978     10     2
28             28 1979-10-10 00:00:00       4/16/2005  1979     10     0
38             38 1984-10-10 22:00:00       8/10/1999  1984     10    22
40             40 1986-10-10 20:00:00       10/8/2007  1986     10    20
...           ...                 ...             ...   ...    ...   ...
80276       80276 2011-09-09 20:30:00       5/13/2012  2011      9    20
80279       80279 2011-09-09 21:15:00      10/10/2011  2011      9    21
80299       80299 2012-09-09 20:10:00       9/24/2012  2012      9    20
80304       80304 2012-09-09 21:00:00       9/24/2012  2012      9    21
80310       80310 2013-09-09 01:50:00       9/30/2013  2013      9     1

       Season Country_Code        Country    Region         Locale   latitude  \
12     Autumn          USA  United States  New York  Nassau County  40.668611
27     Autumn          USA  United States  New York    Alden Manor  40.700833
28     Autumn          USA  United States  New York   Poughkeepsie  41.700278
38     Autumn          USA  United States  New York   White Plains  41.033889
40     Autumn          USA  United States  New York         Holmes  41.523427
...       ...          ...            ...       ...            ...        ...
80276  Autumn          USA  United States  New York      Rochester  43.154722
80279  Autumn          USA  United States  New York        Montauk  41.035833
80299  Autumn          USA  United States  New York    Alden Manor  40.700833
80304  Autumn          USA  United States  New York       New York  40.714167
80310  Autumn          USA  United States  New York        Buffalo  42.886389

       longitude  UFO_shape  length_of_encounter_seconds Encounter_Duration  \
12    -73.527500       DISK                       1800.0            30 min.
27    -73.713333  RECTANGLE                        300.0               5min
28    -73.921389    CHEVRON                        900.0         15 minutes
38    -73.763333  FORMATION                         20.0      15-20 seconds
40    -73.646795    CHEVRON                        180.0          3 minutes
...          ...        ...                          ...                ...
80276 -77.615833     CIRCLE                         60.0               1min
80279 -71.955000   CYLINDER                       2100.0    approx. 35 mins
80299 -73.713333     CIRCLE                        600.0         10 minutes
80304 -74.006389      LIGHT                       1290.0              21:30
80310 -78.878611   TRIANGLE                        180.0          3 minutes

                                             Description
12              silver disc seen by family and neighbors
27     A memory I will never forget that happened men...
28     1/4 moon-like&#44  its &#39chord&#39 or flat s...
38     Saw a hugh object in sky with lights intermitt...
40     Football Field Sized Chevron with bright white...
...                                                  ...
80276  Amber/orange balls 1 following the other chang...
80279  Yellow to orange colors radiating above and be...
80299  Orange lights seen in Elmont&#44 Long Island&#...
80304  Glowing&#44 circular lights visible in the clo...
80310    Massive Flat Black triangle  with 3 red lights.

[3235 rows x 17 columns]