# M1L6 Identifying & Handling Missing Data 

 We'll be working with the same Austin Animal Center Intakes dataset from the previous lecture, which contains information about animals entering the Austin Animal Center.

### **Dataset:** [Austin Animal Center Intakes](https://catalog.data.gov/dataset/austin-animal-center-intakes) -- This is also in your data folder 

### **Objectives:**

 1.  Identify Columns with Missing Data
 2.  Handle missing data by dropping data and using imputation techniques

## Step 1:  Import pandas and numpy

In [1]:
#Import packages 

import pandas as pd
import numpy as np

## Step 2:  Load in the data and save it as `df`

In [2]:
df=pd.read_csv('/Users/Marcy_Student/Downloads/Austin_Animal_Center_Intakes__10_01_2013_to_05_05_2025_.csv')

## Step 3:  Look at the data (can you think of ONE method that we can use to quickly see column names and how many non-null values exist in each column)

**Instructor if they draw a blank say what method can tell us data types, column names, the number of non-null values etc**

In [5]:
df.describe

<bound method NDFrame.describe of        Animal ID    Name                DateTime     MonthYear  \
0        A521520    Nina  10/01/2013 07:51:00 AM  October 2013
1        A664235     NaN  10/01/2013 08:33:00 AM  October 2013
2        A664236     NaN  10/01/2013 08:33:00 AM  October 2013
3        A664237     NaN  10/01/2013 08:33:00 AM  October 2013
4        A664233  Stevie  10/01/2013 08:53:00 AM  October 2013
...          ...     ...                     ...           ...
173807   A929690     NaN  05/03/2025 11:18:00 PM      May 2025
173808   A929717     NaN  05/04/2025 03:14:00 PM      May 2025
173809   A929724     NaN  05/04/2025 07:43:00 PM      May 2025
173810   A929725  Oswold  05/04/2025 10:55:00 PM      May 2025
173811   A929635     NaN  05/04/2025 11:44:00 PM      May 2025

                                  Found Location    Intake Type  \
0                        Norht Ec in Austin (TX)          Stray
1                            Abia in Austin (TX)          Stray
2                            Abia in Austin (TX)          Stray
3                            Abia in Austin (TX)          Stray
4                 7405 Springtime in Austin (TX)          Stray
...                                          ...            ...
173807           8038 Exchange Dr in Austin (TX)          Stray
173808                               Austin (TX)  Public Assist
173809  7105 Providence Ave Apt 3 in Austin (TX)          Stray
173810         1501  Red River St in Austin (TX)  Public Assist
173811              708 Simonetti in Austin (TX)          Stray

       Intake Condition Animal Type Sex upon Intake Age upon Intake  \
0                Normal         Dog   Spayed Female         7 years
1                Normal         Cat         Unknown          1 week
2                Normal         Cat         Unknown          1 week
3                Normal         Cat         Unknown          1 week
4               Injured         Dog   Intact Female         3 years
...                 ...         ...             ...             ...
173807          Injured         Dog     Intact Male         2 years
173808           Normal         Dog     Intact Male          1 year
173809           Normal       Other         Unknown          1 year
173810           Normal         Dog     Intact Male        10 years
173811           Normal         Cat   Spayed Female         2 years

                               Breed         Color
0       Border Terrier/Border Collie     White/Tan
1             Domestic Shorthair Mix  Orange/White
2             Domestic Shorthair Mix  Orange/White
3             Domestic Shorthair Mix  Orange/White
4                       Pit Bull Mix    Blue/White
...                              ...           ...
173807              Belgian Malinois   Brown/Black
173808                  Shih Tzu Mix    White/Blue
173809                     Rabbit Sh     Tan/White
173810                     Boxer Mix     Tan/White
173811            Domestic Shorthair   Black/White

[173812 rows x 12 columns]>

## Step 4:  Assign a missing indicator to those rows who have missing animal names

In [16]:
None
df.head('Missing Name').isnull() #optional line to see changes

TypeError: cannot do positional indexing on RangeIndex with these indexers [Missing Name] of type str

## Step 5:  Many names are missing let's fill this in with "UNKNOWN"

In [13]:
df['Name'].fillna("Unkown",inplace=True)
df.head() #optional line to see changes

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A521520,Nina,10/01/2013 07:51:00 AM,October 2013,Norht Ec in Austin (TX),Stray,Normal,Dog,Spayed Female,7 years,Border Terrier/Border Collie,White/Tan
1,A664235,Unkown,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
2,A664236,Unkown,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
3,A664237,Unkown,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
4,A664233,Stevie,10/01/2013 08:53:00 AM,October 2013,7405 Springtime in Austin (TX),Stray,Injured,Dog,Intact Female,3 years,Pit Bull Mix,Blue/White

## Step 6:  There is ony one column with 'Age' missing; let's drop it for now

In [10]:
df['Sex upon Intake'].isnull().sum
df.info() #optional line to see changes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173812 entries, 0 to 173811
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Animal ID         173812 non-null  object
 1   Name              123821 non-null  object
 2   DateTime          173812 non-null  object
 3   MonthYear         173812 non-null  object
 4   Found Location    173812 non-null  object
 5   Intake Type       173812 non-null  object
 6   Intake Condition  173812 non-null  object
 7   Animal Type       173812 non-null  object
 8   Sex upon Intake   173811 non-null  object
 9   Age upon Intake   173812 non-null  object
 10  Breed             173812 non-null  object
 11  Color             173812 non-null  object
dtypes: object(12)
memory usage: 15.9+ MB

In [11]:
df.dropna(subset= ('Sex upon Intake'))

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A521520,Nina,10/01/2013 07:51:00 AM,October 2013,Norht Ec in Austin (TX),Stray,Normal,Dog,Spayed Female,7 years,Border Terrier/Border Collie,White/Tan
1,A664235,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
2,A664236,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
3,A664237,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
4,A664233,Stevie,10/01/2013 08:53:00 AM,October 2013,7405 Springtime in Austin (TX),Stray,Injured,Dog,Intact Female,3 years,Pit Bull Mix,Blue/White
...,...,...,...,...,...,...,...,...,...,...,...,...
173807,A929690,NaN,05/03/2025 11:18:00 PM,May 2025,8038 Exchange Dr in Austin (TX),Stray,Injured,Dog,Intact Male,2 years,Belgian Malinois,Brown/Black
173808,A929717,NaN,05/04/2025 03:14:00 PM,May 2025,Austin (TX),Public Assist,Normal,Dog,Intact Male,1 year,Shih Tzu Mix,White/Blue
173809,A929724,NaN,05/04/2025 07:43:00 PM,May 2025,7105 Providence Ave Apt 3 in Austin (TX),Stray,Normal,Other,Unknown,1 year,Rabbit Sh,Tan/White
173810,A929725,Oswold,05/04/2025 10:55:00 PM,May 2025,1501 Red River St in Austin (TX),Public Assist,Normal,Dog,Intact Male,10 years,Boxer Mix,Tan/White
173811,A929635,NaN,05/04/2025 11:44:00 PM,May 2025,708 Simonetti in Austin (TX),Stray,Normal,Cat,Spayed Female,2 years,Domestic Shorthair,Black/White